#
# Makefile for the kernel auxiliary displays device drivers.
#

obj-$(CONFIG_KS0108)		+= ks0108.o
obj-$(CONFIG_CFAG12864B)	+= cfag12864b.o cfag12864bfb.o
obj-$(CONFIG_IMG_ASCII_LCD)	+= img-ascii-lcd.o
obj-$(CONFIG_SH1107)		+= sh1107.o
obj-$(CONFIG_OEL9M1027)		+= oel9m1027.o
oel9m1027-y			+= oel9m1027_core.o oel9m1027_fb.o
