# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_ZYNQ) += \
	zynq-cc108.dtb \
	zynq-ebaz4205.dtb \
	zynq-microzed.dtb \
	zynq-parallella.dtb \
	zynq-zc702.dtb \
	zynq-zc706.dtb \
	zynq-zc770-xm010.dtb \
	zynq-zc770-xm011.dtb \
	zynq-zc770-xm012.dtb \
	zynq-zc770-xm013.dtb \
	zynq-zed.dtb \
	zynq-zturn.dtb \
	zynq-zturn-v5.dtb \
	zynq-zybo.dtb \
	zynq-zybo-z7.dtb \
	ni-762F.dtb \
	ni-76D3.dtb \
	ni-76D6.dtb \
	ni-76F2.dtb \
	ni-7740.dtb \
	ni-7741.dtb \
	ni-7742.dtb \
	ni-7743.dtb \
	ni-7744.dtb \
	ni-774C.dtb \
	ni-774E.dtb \
	ni-775E.dtb \
	ni-77AC.dtb \
	ni-77B1.dtb \
	ni-77B2.dtb \
	ni-77D4.dtb \
	ni-77D5.dtb \
	ni-77D6.dtb \
	ni-7885.dtb \
	ni-793C.dtb \
	ni-7AAE.dtb
